apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nextcloud-var
  namespace: argocd
spec:
  description: App of Apps project with multi-environment support

  sourceRepos:
    - '*'

  destinations:
    # Allow ArgoCD internal apps
    - namespace: argocd
      server: https://kubernetes.default.svc

    # Workload namespaces
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
    - namespace: nextcloud
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

