apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-var-ingress
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: $(INGRESS_HOST)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-var
                port:
                  number: 80

