apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-var-mariadb
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-var-mariadb
  template:
    metadata:
      labels:
        app: nextcloud-var-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          envFrom:
            - secretRef:
                name: nextcloud-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-nfs-pvc-var

