apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-var
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-var
  template:
    metadata:
      labels:
        app: nextcloud-var
    spec:
      containers:
        - name: nextcloud-var
          image: nextcloud:27
          env:
            - name: MYSQL_HOST
              value: nextcloud-var-mariadb
            - name: REDIS_HOST
              value: nextcloud-var-redis
          volumeMounts:
            - name: data
              mountPath: /var/www/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-nfs-pvc-var

