apiVersion: v1
kind: PersistentVolume
metadata:
  name: $(PV_NAME)
spec:
  capacity:
    storage: $(PV_SIZE)
  accessModes:
    - ReadWriteMany
  storageClassName: $(STORAGE_CLASS)
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: $(NFS_SERVER)
    path: $(NFS_PATH)

