apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-pv-var
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-var
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.2.218
    path: /srv/nfs/k8s/nextcloud-var

