apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $(PVC_NAME)
  namespace: $(NAMESPACE)
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: $(STORAGE_CLASS)
  resources:
    requests:
      storage: $(PV_SIZE)

