apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-pvc-var
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-var
  resources:
    requests:
      storage: 50Gi

