apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $(PVC_NAME)
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: $(STORAGE_CLASS)
  resources:
    requests:
      storage: 50Gi

