apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-var-redis
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-var-redis
  template:
    metadata:
      labels:
        app: nextcloud-var-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4.2
          args: ["redis-server","--appendonly","yes"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-nfs-pvc-var

